[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 4

# Social Media Configuration

[[social]]
    identifier = "linkedin"
    name = "https://linkedin.com/in/anosikeosifo"
    url = "#"
    weight = 1

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/osifo"
    weight = 2

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/osifo__"
    weight = 3
